// <auto-generated />
namespace ContactList_MVVM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RequiredRuleAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequiredRuleAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201812271916363_RequiredRuleAdd]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
